### ISSUE TITLE
Can't load fawkes with tensorflow-gpu

### ISSUE THREAD

**Issue by M4cs** [Shawn-Shan/fawkes#24]
Initially I ran `setup.py` with the `tensorflow-gpu` package commented out.

When trying to run fawkes with the `tensorflow` package installed I'd get this output:

**Ran:** `fawkes -d .\img --mode custom --format png --lr 0.0001 --max-step 1000 -g 0`

**no tensorflow-gpu installed**

```
2020-07-24 13:36:34.490847: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 13:36:46.546924: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-24 13:36:46.549821: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-07-24 13:36:46.581144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:08:00.0
2020-07-24 13:36:46.581246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 13:36:46.583749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-07-24 13:36:46.618641: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-07-24 13:36:46.629692: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-07-24 13:36:46.633331: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-07-24 13:36:46.668471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-07-24 13:36:46.681224: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 13:36:46.681384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-07-24 13:36:47.218796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-24 13:36:47.218883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-07-24 13:36:47.218986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-07-24 13:36:47.219192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6679 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)
2020-07-24 13:36:47.221479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:08:00.0
2020-07-24 13:36:47.221551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 13:36:47.221591: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-07-24 13:36:47.221629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-07-24 13:36:47.221666: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-07-24 13:36:47.221703: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-07-24 13:36:47.221740: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-07-24 13:36:47.221778: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 13:36:47.221844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-07-24 13:36:47.221910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-24 13:36:47.221948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-07-24 13:36:47.221977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-07-24 13:36:47.222070: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6679 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)
Identify 1 files in the directory
Identify 1 images in the directory
2020-07-24 13:36:58.168878: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 13:36:59.043381: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-07-24 13:36:59.046724: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node pnet/conv1/Conv2D}}]]
         [[pnet/prob1/_3729]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node pnet/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
```

Now when I run it with `tensorflow-gpu` installed and `tensorflow` uninstalled first it doesn't even load my GPU or try to load cudNN. It just says it couldn't initalize cudNN and fails to find the convolution algorithm.

**Comment by Shawn-Shan** [comment]
You mean you installed tensorflow-gpu right, which version are you using?

**Comment by M4cs** [comment]
Yes when I installed `tensorflow-gpu` 1.14.0 it wouldn't even attempt to load my GPU device

**Comment by Shawn-Shan** [comment]
I see, it seems it recognize the GPU but have some issue loading it. I need a bit more details to provide a solution. 
What OS are you using? Have you successfully use tensorflow-gpu on your GPU before? Can you train `pip uninstall tensorflow-gpu` and then `pip install tensorflow-gpu==1.14.0`

**Comment by M4cs** [comment]
Yes I'm able to run other tensorflow applications and load cudNN and my GPU fine.

When I have `tensorflow=1.15.0` installed and no `tensorflow-gpu` package in my virtualenv running:

```
fawkes -d img --mode custom -g 0 --format png --lr 0.0001
```

Produces this output:

```
2020-07-24 21:15:24.741918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 21:15:27.957029: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-24 21:15:27.995310: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-07-24 21:15:28.072269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:08:00.0
2020-07-24 21:15:28.073358: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 21:15:28.078300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-07-24 21:15:28.083635: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-07-24 21:15:28.096402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-07-24 21:15:28.109924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-07-24 21:15:28.113625: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-07-24 21:15:28.124704: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 21:15:28.128501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-07-24 21:15:38.237753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-24 21:15:38.238003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-07-24 21:15:38.238284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-07-24 21:15:38.263455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6679 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)
2020-07-24 21:15:38.421302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:08:00.0
2020-07-24 21:15:38.421798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-07-24 21:15:38.422002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-07-24 21:15:38.422146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-07-24 21:15:38.422276: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-07-24 21:15:38.422396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-07-24 21:15:38.422527: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-07-24 21:15:38.422671: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 21:15:38.434560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-07-24 21:15:38.434836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-24 21:15:38.435009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-07-24 21:15:38.435233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-07-24 21:15:38.435469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6679 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)
Identify 1 files in the directory
Identify 1 images in the directory
2020-07-24 21:15:53.083830: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-24 21:15:56.151685: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-07-24 21:15:56.152519: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[{{node pnet/conv1/Conv2D}}]]
         [[pnet/prob1/_3729]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[{{node pnet/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\fawkes\.aienv\Scripts\fawkes-script.py", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.1.0', 'console_scripts', 'fawkes')())
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 206, in main
    separate_target=args.separate_target, debug=args.debug)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 106, in run_protection
    faces = Faces(image_paths, loaded_images, self.aligner, verbose=1)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\utils.py", line 130, in __init__
    align_img = align(cur_img, self.aligner, margin=margin)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\align_face.py", line 32, in align
    bounding_boxes, _ = run_detect_face(orig_img, minsize, pnet, rnet, onet, threshold, factor)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 319, in run_detect_face
    out = pnet(img_y)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 281, in <lambda>
    pnet_fun = lambda img: sess.run(('pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0'), feed_dict={'pnet/input:0': img})
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[node pnet/conv1/Conv2D (defined at \lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\ops.py:1748) ]]
         [[pnet/prob1/_3729]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[node pnet/conv1/Conv2D (defined at \lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'pnet/conv1/Conv2D':
  File "\Scripts\fawkes-script.py", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.1.0', 'console_scripts', 'fawkes')())
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 203, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 60, in __init__
    self.aligner = aligner(sess)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\align_face.py", line 16, in aligner
    pnet, rnet, onet = create_mtcnn(sess, None)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 268, in create_mtcnn
    pnet = PNet({'data': data})
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 52, in __init__
    self.setup()
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 198, in setup
    .conv(3, 3, 10, 1, 1, padding='VALID', relu=False, name='conv1')
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 29, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 134, in conv
    output = convolve(inp, kernel)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 130, in <lambda>
    convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\ops\nn_ops.py", line 2010, in conv2d
    name=name)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\ops\gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "\lib\site-packages\tensorflow-1.15.0-py3.7-win-amd64.egg\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

Next I run:

```
pip uninstall tensorflow-gpu tensorflow
```

It uninstalls and then I run with setup.py having the tensorflow-gpu line uncommented and the normal tensorflow package requiremented commented out:

```
python setup.py install
```

It installs `tensorflow-gpu==1.14.0`, I then run:

```
fawkes -d img --mode custom -g 0 --format png --lr 0.0001
```

and the output is:

```
Identify 1 files in the directory
Identify 1 images in the directory
Traceback (most recent call last):
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[{{node pnet/conv1/Conv2D}}]]
         [[pnet/prob1/_3729]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[{{node pnet/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\fawkes\.aienv\Scripts\fawkes-script.py", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.1.0', 'console_scripts', 'fawkes')())
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 206, in main
    separate_target=args.separate_target, debug=args.debug)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 106, in run_protection
    faces = Faces(image_paths, loaded_images, self.aligner, verbose=1)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\utils.py", line 130, in __init__
    align_img = align(cur_img, self.aligner, margin=margin)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\align_face.py", line 32, in align
    bounding_boxes, _ = run_detect_face(orig_img, minsize, pnet, rnet, onet, threshold, factor)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 319, in run_detect_face
    out = pnet(img_y)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 281, in <lambda>
    pnet_fun = lambda img: sess.run(('pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0'), feed_dict={'pnet/input:0': img})
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "F:\Downloads\fawkes\.aienv\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[node pnet/conv1/Conv2D (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:130) ]]
         [[pnet/prob1/_3729]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.       
         [[node pnet/conv1/Conv2D (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:130) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node pnet/conv1/Conv2D:
 pnet/conv1/weights/read (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:103)
 pnet/input (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:267)

Input Source operations connected to node pnet/conv1/Conv2D:
 pnet/conv1/weights/read (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:103)
 pnet/input (defined at \lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py:267)

Original stack trace for 'pnet/conv1/Conv2D':
  File "\Scripts\fawkes-script.py", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.1.0', 'console_scripts', 'fawkes')())
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 203, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\protection.py", line 60, in __init__
    self.aligner = aligner(sess)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\align_face.py", line 16, in aligner
    pnet, rnet, onet = create_mtcnn(sess, None)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 268, in create_mtcnn
    pnet = PNet({'data': data})
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 52, in __init__
    self.setup()
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 198, in setup
    .conv(3, 3, 10, 1, 1, padding='VALID', relu=False, name='conv1')
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 29, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 134, in conv
    output = convolve(inp, kernel)
  File "\lib\site-packages\fawkes-0.1.0-py3.7.egg\fawkes\detect_faces.py", line 130, in <lambda>
    convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\ops\nn_ops.py", line 1953, in conv2d
    name=name)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\ops\gen_nn_ops.py", line 1161, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "\lib\site-packages\tensorflow_gpu-1.14.0-py3.7-win-amd64.egg\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```


Notice the lack of it trying to load GPU devices on the `tensorflow-gpu` package but not the `tensorflow` package? I've never experienced an issue like this before.

Within the python shell the tensorflow package has no problem finding and listing my GPU:
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.client import device_lib
>>> print(device_lib.list_local_devices())
2020-07-24 21:21:26.896740: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-24 21:21:26.899479: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2020-07-24 21:21:26.930369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:08:00.0
2020-07-24 21:21:26.930715: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-07-24 21:21:26.930922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-07-24 21:21:27.359107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-24 21:21:27.359343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2020-07-24 21:21:27.359577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2020-07-24 21:21:27.359920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 6687 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5)
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10990172601894727512
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 7012129178
locality {
  bus_id: 1
  links {
  }
}
incarnation: 9526483785233859335
physical_device_desc: "device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:08:00.0, compute capability: 7.5"
]
```

**Comment by M4cs** [comment]
Environment Specs:

OS: Windows 10
Python Version: 3.7.3 virtualenv

**Comment by Shawn-Shan** [comment]
Thanks for the additional info. Can you try uninstall all `tensorflow` and `tensorflow-gpu` on your system (both in and outside virtualenv), and reinstall `tensorflow-gpu==1.14.0`

**Comment by M4cs** [comment]
Running into the same issue after doing so.

**Comment by zidielucky** [comment]
您好，请问下这个怎么解决呢？
PS F:\job1\fawkes_binary_windows-v0.2 (1)> .\protection-v0.2.exe -d F:/job1/fawkes_img
Traceback (most recent call last):
  File "fawkes\protection.py", line 210, in <module>
  File "fawkes\protection.py", line 203, in main
  File "fawkes\protection.py", line 61, in __init__
  File "fawkes\protection.py", line 61, in <listcomp>
  File "fawkes\utils.py", line 367, in load_extractor
  File "keras\engine\saving.py", line 492, in load_wrapper
  File "keras\engine\saving.py", line 583, in load_model
  File "keras\utils\io_utils.py", line 191, in __init__
  File "h5py\_hl\files.py", line 408, in __init__
  File "h5py\_hl\files.py", line 173, in make_fid
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 9510912, sblock->base_addr = 0, stored_eof = 29292232)
[1828] Failed to execute script protection
PS F:\job1\fawkes_binary_windows-v0.2 (1)>

**Comment by emjoywill** [comment]
@M4cs it seems like this may be an issue with cuDNN. Have you previously installed cuDNN?

**Comment by M4cs** [comment]
> 
> 
> @M4cs it seems like this may be an issue with cuDNN. Have you previously installed cuDNN?

Yes, I have cuDNN installed and it works with other tensorflow projects. It's CUDA 10.

**Comment by emjoywill** [comment]
I've done some poking around and the only time that I've gotten a similar error msg to the one you're showing is when I install tensorflow==1.15.0. In that situation, cuDNN fails to initialize. Downgrading to tensorflow==1.14.0 solves the issue. 

Perhaps working in a virtualenv would make it easier to ensure this it not a versioning error. Could you try creating a virtualenv, installing tensorflow-gpu==1.14.0 there, and then running the Fawkes setup.py?

**Comment by M4cs** [comment]
I have it setup in a virtualenv, I've installed only 1.14.0 tensorflow and it still wont work.

**Comment by Chroisa** [comment]
I got it to work with:

tensorflow-gpu: 1.14.0
cuda: 10.0 (not 10.1)
cudnn: 7.5.0.56

Detailed steps, sample runs, setup script, original/result files, etc. for GCE coming up on my LinkedIn channel:

(https://www.linkedin.com/in/marenpeasley/detail/recent-activity/shares/)

**Comment by Chroisa** [comment]
Setup script on Google Compute Engine until I can get the article written:
https://docs.google.com/document/d/1hSdpD04N5LvMVr74Xg-0vkm_R3FK0s0xaWuTNxNO4fM/edit?usp=sharing
